version: "3.9"

services:
  postgres-database:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=products-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=9999
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 7s
      timeout: 5s
      retries: 3
  app:
    image: data-processor:latest
    depends_on:
      postgres-database:
        condition: service_healthy
